@startuml

[*] --> Main_Menu
Main_Menu: Menu Utama
Main_Menu: 1. Makanan
Main_Menu: 2. Minuman
Main_Menu: 3. Exit
Main_Menu: Pilih menu

Main_Menu --> Makanan: Pilihan 1
Main_Menu --> Minuman: Pilihan 2
Main_Menu --> [*]: Pilihan 3 (Exit)

Makanan: Menu Makanan
Makanan: 1. Pecel Lele
Makanan: 2. Nasi Goreng
Makanan: 3. Kembalir
Makanan: Pilih menu makanan

Minuman: Menu Minuman
Minuman: 1. Teh Manis
Minuman: 2. Air Putih
Minuman: 3. Kembali
Minuman: Pilih menu minuman

Makanan --> Main_Menu: Kembali (Pilihan 3)
Minuman --> Main_Menu: Kembali (Pilihan 3)

Makanan --> Hitung_Total_Makanan: Memilih makanan
Minuman --> Hitung_Total_Minuman: Memilih minuman

Hitung_Total_Makanan: Masukkan jumlah pesanan
Hitung_Total_Makanan: Hitung total harga
Hitung_Total_Minuman: Masukkan jumlah pesanan
Hitung_Total_Minuman: Hitung total harga

Hitung_Total_Makanan --> Makanan: Kembali
Hitung_Total_Minuman --> Minuman: Kembali

Main_Menu --> [*]: Exit

@enduml
